name: flutterapp
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_treeview: '^1.0.7+1'
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.3.1
  google_ml_kit: ^0.19.0
  video_player: ^2.4.5 
  flick_video_player: ^0.9.0 
  cupertino_icons: ^1.0.2
  csslib: ^1.0.0
  flutter_staggered_grid_view: 0.7.0
  carousel_slider: ^5.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/RadixVidSort.mp4
    - assets/Learn.png
    - assets/Simulation.png
    - assets/Game.png
    - assets/block-6839.ogg
